add references for staff cost and billable rates
Accelo/docs pull request #131
Opened 2021-10-27 04:24 UTC by marcusaccelo

2021-10-31 22:28 UTC, Timothy-Edwards requested changes
Thanks for putting this up @marcusaccelo! Just a couple of comments, let me know if you need a hand with any of them

2021-10-31 22:28 UTC, Timothy-Edwards commented on source/includes/endpoints/_staff.md
> +### Get Billable and Cost Rates on a Staff
@marcusaccelo I think it might be best to add these fields to the existing staff field list here https://github.com/Accelo/docs/pull/131/files#diff-1c946adc1b00081883a0d7db9078c710cbcc52efcaa5125726bf56e0bf057b05R27

2021-10-31 22:28 UTC, Timothy-Edwards commented on source/includes/endpoints/_staff.md
> +| staff_rate | The staff member's billable rate. |
It would be good if we could add the type of the fields here as well. In both cases I think it should be `decimal`

2021-10-31 22:28 UTC, Timothy-Edwards commented on source/includes/endpoints/_tasks.md
> +### List Skills on a Task
Similar to the staff object, it would be good to add these fields to the existing list of available fields on a task.

Would also be good to add a type and description on this field. 

eg. in this case, the type would be `array[object]` or something like that :)

2021-11-01 20:07 UTC, marcusaccelo commented on source/includes/endpoints/_staff.md
> +### Get Billable and Cost Rates on a Staff
Thanks for taking a look @Timothy-Edwards! I'll get these adjustments made. I did want to double-check though, as the staff rates and task skills fields aren't returned on the object by default (aren't returned when requesting `_ALL` fields) and are only returned when requesting those fields explicitly. Due to that I wasn't sure if I should put them with the rest of the fields that _do_ get returned by default. Happy to update it either way, just lmk!

2021-11-01 21:49 UTC, Timothy-Edwards commented on source/includes/endpoints/_staff.md
> +### Get Billable and Cost Rates on a Staff
The fields returned by default are made bold in the table, it might be worth putting a note in the description that they won't be returned by _ALL though :)

2021-11-02 20:26 UTC, marcusaccelo commented on source/includes/endpoints/_tasks.md
> +### List Skills on a Task
I've committed these changes, please let me know if there's anything else you need from me or if I should open a new pull request. Thanks again!

2021-11-03 22:11 UTC, Timothy-Edwards approved these changes

2021-11-03 22:11 UTC, Timothy-Edwards commented
Looks good, thanks marcus!

2021-11-03 22:11 UTC, merged