Update _tasks.md
Accelo/docs pull request #145
Opened 2022-07-22 03:38 UTC by nick-clark84

Added | date_started | to line 565
added | started | to line 256

As per instruction in https://affinitylive.jira.com/browse/AFFINITY-35257

2022-07-22 04:20 UTC, Timothy-Edwards requested changes
A couple of things from me, let me know if you need a hand with anything

2022-07-22 04:20 UTC, Timothy-Edwards commented on source/includes/endpoints/_tasks.md
> +##### Basics
@nick-clark84 Should this still be `Basic Filters` for consistency with other filters?

2022-07-22 04:20 UTC, Timothy-Edwards commented on source/includes/endpoints/_tasks.md
> +| started |
@nick-clark84 Looks like the started filter is already documented on line 250?

2022-07-22 04:32 UTC, nick-clark84 commented on source/includes/endpoints/_tasks.md
> +##### Basics
Hi @Timothy-Edwards sorry I don't think I meant to make this change. I have a feeling I inadvertently remove **Filters** when I` ctrl+f `in the doc for Filters. 

Can "cancel" this change.

2022-07-22 04:35 UTC, nick-clark84 commented on source/includes/endpoints/_tasks.md
> +| started |
Hi @Timothy-Edwards yep `date_started` is on line 250, I thought your comment [here](https://affinitylive.jira.com/browse/AFFINITY-35257?focusedCommentId=124965) was suggesting that `started` should be its own unique filter

2022-07-22 05:24 UTC, cebjyre commented on source/includes/endpoints/_tasks.md
> +##### Basics
```suggestion
##### Basic Filters
```

2022-07-22 05:29 UTC, cebjyre commented on source/includes/endpoints/_tasks.md
> +| started |
Not wanting to put words in Tim's mouth, but I suspect that comment was meant more as "if we are missing it from the update-able field list, we may also be missing it from the described filters list, so that might need to be added too" (and then he left off the "date_" part to confuse matters)
```suggestion
```

2022-07-24 23:40 UTC, Timothy-Edwards commented on source/includes/endpoints/_tasks.md
> +| started |
@nick-clark84 Yeah, sorry glenn is correct. `date_started` is the correct format for all the date filters. My bad I should have been clearer 🤦🏼

2025-11-03 00:02 UTC, pfbaz approved these changes

2025-11-03 00:03 UTC, merged