Update _introduction.md
Accelo/docs pull request #158
Opened 2023-09-25 00:07 UTC by nick-clark84

Adding details about the cipher suites & Application Load Balancer.

2023-09-25 00:56 UTC, cebjyre requested changes
I don't love the technical details that seem way too likely to become incorrect

2023-09-25 00:56 UTC, cebjyre commented on source/includes/_introduction.md
> +* ECDHE-RSA-AES256-GCM-SHA384
This seems overly technical, and likely to become stale (eg do we really not support TLS 1.3?) - I'd lean more towards a general statement of using secure ciphers, maybe with reference to something that lists insecure ciphers that we no longer support (AWS docs of "don't use this" if such a page exists)

2023-09-25 01:53 UTC, Timothy-Edwards commented on source/includes/_introduction.md
> +## API Application Load Balancer (ALB)
This heading might be better as `Cipher Suites` or similar rather than being load balancer specific.

2023-09-25 01:53 UTC, Timothy-Edwards requested changes
Plus 1 to Glenn's comments. Also one minor thing from me re. the section title.

2023-09-25 01:55 UTC, Timothy-Edwards commented on source/includes/_introduction.md
> +* ECDHE-RSA-AES256-GCM-SHA384
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html#:~:text=your%20load%20balancer.-,Security%20policies,-Elastic%20Load%20Balancing Might do the trick

2023-09-25 03:46 UTC, nick-clark84 commented on source/includes/_introduction.md
> +## API Application Load Balancer (ALB)
Hi @Timothy-Edwards sounds good. Can I update this from here?

2023-09-25 23:12 UTC, Timothy-Edwards submitted a review, later dismissed

2023-09-26 00:46 UTC, cebjyre requested changes

2023-09-26 00:46 UTC, cebjyre commented on source/includes/_introduction.md
> +https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html
```suggestion
In order to maintain security for Accelo and our customers, we may need to stop using old cipher suites; this could cause problems for users utilising older SSL/TLS libraries.
Before doing so we will ensure that this will not affect the majority of our users, and will work with those that would be impacted.
See the below link for technical details, as of 2023 we are using `ELBSecurityPolicy-FS-1-2-Res-2019-08`. 
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html#fs-supported-policies
```
@nick-clark84 I did a rewrite; @bretthagelstein are you happy with this level of info?

2023-09-26 01:01 UTC, bretthagelstein commented on source/includes/_introduction.md
> +https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html
Please update the cipher name to `ELBSecurityPolicy-FS-1-2-Res-2020-10` and I'm on board

2023-09-26 01:40 UTC, cebjyre approved these changes
I approve of my own work, seems pretty good

2023-09-26 01:41 UTC, Timothy-Edwards approved these changes

2023-09-26 06:27 UTC, merged